### ISSUE TITLE
Command-line argument parsers: experiences with two choices

### ISSUE THREAD

**Issue by emk** [production-rs/bikeshed#10]
At Faraday, we use two of these:

- [docopt](https://docs.rs/docopt/0.7.0/docopt/) is great when we just want to throw together a simple CLI with few options and maybe a subcommand or two. Works beautifully and takes just a few seconds.
- [clap](https://docs.rs/clap/2.20.1/clap/) is more verbose and complicated to set up, but if you've hit the limits of `docopt`, this is _definitely_ the way to go. This can handle complex, `git`-style subcommands, and you can specify the options with YAML.

The advantage of `doctopt` is basically that it's a no-brainer: You can have it up and running in 2 or 3 minutes, so there's no excuse not to use it.

**Comment by stephanbuys** [comment]
We've used `clap` exclusively, I'd vote for it. The idea of the list is to pick one for beginners as a recommendation, so, do we add a 'simple cli' category or pick one - and in that case which one?

**Comment by emk** [comment]
I think this question is going to come up for more than one category, and this is as good a time to talk about it as any.

In some sense, this project potentially combines two functions:

1. Documenting what production users of Rust actually use successfully in production.
2. Making somewhat opinionated recommendations about good default choices.

Both are valuable individually, but I think that they're even more valuable when combined: When production users of Rust really have ended up settling on two major, popular choices in a certain area (with say 60% and 30% usage, respectively), I think it's extremely useful to mention which library is most popular, but to also describe any highly-popular runner up and why people might want to use it.

A good example in the Ruby world of such a split might be `Test::Unit` (the default choice in Rails) versus `RSpec` (an extremely popular minority choice that's held significant market share for the better part of 10 years).

In some cases, we might split a category to avoid this issue (for example, "simple CLIs" and "complex CLIs"). But I think we should definitely consider what to do if a given category has a 60/30 split (with interesting tradeoffs) among production users.

**Comment by stephanbuys** [comment]
Agreed, I imagined a scenario where something might be popular, stable and in wide-spread use but 'waning', another might be 'up and coming' and thirdly a 'solid choice', perhaps there is place for 3 categories. Up and coming might be a referral to awesome-rust or something similar?

For example, `rustc-serialize` would be 'waning', `serde` would be the current production choice and something like `nom`? might be 'up-and-coming'?

It would be cool to at some point have a per-crate write-up/motivation.

**Comment by emk** [comment]
`nom` is really in a different category than `serde`. `serde` is for automatic serialization to standardized formats, like YAML or JSON or whatever. `nom` is a parser generator for messy byte- and bit-oriented protocols that need to be picked apart one piece at a time.

But yeah, it would be nice to write something like:

> Recommended: `serde`. Fast, customizable and easy to use in simple cases. Earlier, the most popular choice was `rustc-serialize`, which has built-in compiler support.

...or whatever.

The more production users we get together, the more we can compare notes. And when `cargo-esr` is ready, we should also check the scores it generates.

> It would be cool to at some point have a per-crate write-up/motivation.

In the long run, this is the most valuable thing we can bring to the table, I think—real world experience. Other projects will handle automatic "scoring" of popular crates.

**Comment by stephanbuys** [comment]
Ok, so may I suggest something like `alternate`? We can mention that `alternate` crates are sometimes older crates that are being superseded or a popular alternative choice (just as valid but a little different in its approach).

**Comment by emk** [comment]
Yeah! That seems about right. I think that `alternate` crates can be included **if** the alternate is genuinely popular, with either good download counts or production use. We might want to be suspicious about listing an alternate if it has less than, say, 20% market share. The only time we might list three possibilities was when the real-world use was a 45/25/25 split, but that would almost require a note explaining what's going on. I think that's rare, though—the two most common patterns are either:

1. Everybody agrees on the "right" choice.
2. There's one popular choice, and a second alternate choice that's used widely.

In this case, `clap` has 410,361 downloads and `docopt` has 401,051, so it's nearly a 50/50 split. I'm comfortable with `clap` as the primary (because it handles complex subcommands better) and `docopt` as the alternate.
