### ISSUE TITLE
Additional Category: Testing

### ISSUE THREAD

**Issue by alexduer** [production-rs/bikeshed#13]
An important part software engineering is testing. In my opinion there should be a testing category or at least a mention of test frameworks in one of the other categories.

**Comment by stephanbuys** [comment]
@alexduer Thats a great point, I'll create some categories.

**Comment by stephanbuys** [comment]
@alexduer some nominations and suggestions for the actual sub categories would be greatly appreciated. Have a look at: https://github.com/production-rs/bikeshed#testing

**Comment by alexduer** [comment]
The only sub category I would add is "Mocking".
