### ISSUE TITLE
Nomination for "Random Numbers"

### ISSUE THREAD

**Issue by pwoolcoc** [production-rs/bikeshed#2]
I'm just curious why the "Random Numbers" slot is open, seems that the `rand` crate from the nursery would be the choice here: https://github.com/rust-lang-nursery/rand

**Comment by stephanbuys** [comment]
Thanks for the suggestion, some categories have clear choice - but were brought to my attention as categories (not crates), I've either not had a chance to fill them in or I've just been unaware.

Added in https://github.com/production-rs/bikeshed/commit/f4a10be77267c72c91d6d37cf47569abb299e0e5
